name: Python application

on:
  push:
    branches: [ "main", "*", "*/*" ]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ "main", "*", "*/*" ]

permissions:
  contents: read
  pull-requests: write


jobs:
  autopep8:
    # Check if the PR is not from a fork
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.head_ref }}
      - name: autopep8
        id: autopep8
        uses: peter-evans/autopep8@v1
        with:
          args: --exit-code --recursive --in-place --aggressive --aggressive .
      - name: Commit autopep8 changes
        if: steps.autopep8.outputs.exit-code == 2
        run: |
          git config --global user.name 'Peter Evans'
          git config --global user.email 'peter-evans@users.noreply.github.com'
          git commit -am "Automated autopep8 fixes"
          git push

build:
  runs-on: ubuntu-latest
  needs: autopep8
  steps:
  - uses: actions/checkout@v3
  - name: Set up Python 3.11
    uses: actions/setup-python@v3
    with:
      python-version: "3.11"
  - name: Install dependencies
    run: |
      python -m pip install --upgrade pip
      pip install flake8 pytest
      if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
  - name: Lint with flake8
    run: |
      flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
